FROM kibana
COPY conf/kibana.yml /etc/kibana.yml
#RUN /usr/share/kibana/bin/kibana-plugin install x-pack
#RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.7/logtrail-5.x-0.1.7.zip
